# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadSecureFile@1
  name: wdConfig
  inputs:
    secureFile: "WebDeploy.pubxml"
    
- script: |
    echo Copying $(wdConfig.secureFilePath)" file to $(Build.Repository.LocalPath)\MyWebsite\MyWebsite\Properties\PublishProfiles
    mkdir $(Build.Repository.LocalPath)\MyWebsite\MyWebsite\Properties\PublishProfiles
    copy $(wdConfig.secureFilePath) $(Build.Repository.LocalPath)\MyWebsite\MyWebsite\Properties\PublishProfiles\WebDeploy.pubxml
  displayName: "Move config to directory"

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'msbuild'
    arguments: '$(Build.Repository.LocalPath)\MyWebsite\MyWebsite.sln -restore:true /p:DeployOnBuild=true /p:PublishProfile=WebDeploy /p:Configuration=Release /p:Platform="Any CPU" /p:Password=$(webDeployPassword)'

# - task: MSBuild@1
#   displayName: "Deployment via Web Deploy"
#   inputs:
#     solution: '**/*.sln'
#     msbuildArchitecture: 'x64'
#     platform: 'Any CPU'
#     configuration: 'Release'
#     msbuildArguments: '-restore:true /p:DeployOnBuild=true /p:PublishProfile=WebDeploy /p:Password=$(webDeployPassword)'
#     restoreNugetPackages: true