# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadSecureFile@1
  name: wdConfig
  inputs:
    secureFile: "WebDeploy.pubxml"
    
- script: |
    'echo Copying $(wdConfig.secureFilePath)" file to publish profiles'
    'mkdir $(Build.Repository.LocalPath)\MyWebsite\MyWebsite\Properties\PublishProfiles'
    'copy $(wdConfig.secureFilePath) $(Build.Repository.LocalPath)\MyWebsite\MyWebsite\Properties\PublishProfiles\WebDeploy.pubxml'
  displayName: "Move config to directory"

- task: MSBuild@1
  displayName: "Deployment via Web Deploy"
  inputs:
    solution: '**/*.sln'
    msbuildArchitecture: 'x64'
    platform: 'Any CPU'
    configuration: 'Release'
    msbuildArguments: |
      '/p:DeployOnBuild=true'
      '/p:PublishProfile=WebDeploy'
      '/p:Password=$(webDeployPassword)'
    restoreNugetPackages: true